require 'sinatra/activerecord'
require 'sinatra/activerecord/rake'
require './models/user.rb'
require './models/post.rb'
require './models/category.rb'
require './models/comment.rb'
require './models/done.rb'
require './models/follow.rb'